### ISSUE TITLE
Discord bot is not reporting new articles and not responding to commands

### ISSUE THREAD

**Issue by hyperrecursive** [Scaleios/Galnet-Newsfeed#7]
All new articles after 15.10.2020 were not delivered to discord.

`@Galnet News search --after 10-10-2020` never returns a result.

![image](https://user-images.githubusercontent.com/12224339/96621830-654b5000-1309-11eb-8cfb-40c661d1ee34.png)

**Comment by HassanAbouelela** [comment]
Thank you for your report, looking into this at the moment.

**Comment by HassanAbouelela** [comment]
A bit of an update on this:
I'm done investigating, and determined the root cause to be an error with the input. The function expects the time input to be in the form: `after=0000-00-00` (year-month-day), whereas you gave it `after 00-00-0000` (day-month-year with an extra space). At the moment, this fails silently.

What I will do is provide some feedback on malformed input, so you aren't left wondering. In terms of making the program more friendly, I am currently working on allowing more input formats (see #5).

**Comment by hyperrecursive** [comment]
Hey, thanks for investigating. I also have received new articles in the feed, so I will close this issue now and continue to follow #8.
